### ISSUE TITLE
requirements.txtへの対応

### ISSUE THREAD

**Issue by ankurugranpa** [kamesan1577/geek-camp-vol8#29]
GitHub workflowでpoetryからrequirements.txtを生やすのはどう？

docker方面では、レイヤ数とコンテナサイズを誤差程度かもだけど減らせるようになる。
あとビルド時間が減らせるはず

**Comment by kamesan1577** [comment]
これってビルド時に標準の機能使えばpoetryインストールしなくて済んで嬉しいって認識で合ってる？
そうだとしたら確かに嬉しいかも

**Comment by ankurugranpa** [comment]
たぶんその認識
ライブラリのインストールを`pip install -r  requirements.txt`で行けると`poetry`をdocker内でインストールしなくてよくなる
って話
requirements.txt自体は簡単にpoetryから生やせるからどうかなと思った

**Comment by kamesan1577** [comment]
良さそう
docker周り触るの怖いから任せてもいい？

**Comment by ankurugranpa** [comment]
ok

**Comment by kamesan1577** [comment]
助かる
