### ISSUE TITLE
共通のエラーメッセージ

### ISSUE THREAD

**Issue by kamesan1577** [kamesan1577/geek-camp-vol8#39]
予期しないエラーの発生時にユーザーにエラーを明示する共通のメッセージをどこかに置いておくべき……かな？

**Comment by ankurugranpa** [comment]
これdiscord.pyベースのエラーのみを拾う認識？
それともsqliteとかのエラー(discord.pyやsqlite等アプリケーション全体のエラー)も拾う?

**Comment by ankurugranpa** [comment]
`raise_error`と`hello_error`コマンドでエラーがとりあえず呼び出せます
hello.py見ると使い方わかるはず
このissueこう言うことで良き?
